/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/components/base64Conver/ConversionCard" |
       "/pages/components/base64Conver/base64Conver" |
       "/pages/components/convertCurrency/convertCurrency" |
       "/pages/components/deviceInfo/deviceInfo" |
       "/pages/components/networkInfo/networkInfo" |
       "/pages/components/qrcodeShare/qrcodeShare" |
       "/pages/components/randomNumber/randomNumber" |
       "/pages/components/relativeCalculator/relativeCalculator" |
       "/pages/components/timeNow/timeNow" |
       "/pages/components/unitConvert/unitConvert";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
