/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/components/base64Conver/base64Conver" |
       "/pages/components/birthdayCalculator/birthdayCalculator" |
       "/pages/components/convertCurrency/convertCurrency" |
       "/pages/components/countdown/countdown" |
       "/pages/components/deviceInfo/deviceInfo" |
       "/pages/components/discountCalculator/discountCalculator" |
       "/pages/components/matchCalculator/matchCalculator" |
       "/pages/components/networkInfo/networkInfo" |
       "/pages/components/numberMerge/numberMerge" |
       "/pages/components/qrcodeShare/qrcodeShare" |
       "/pages/components/randomDecider/randomDecider" |
       "/pages/components/randomNumber/randomNumber" |
       "/pages/components/relativeCalculator/relativeCalculator" |
       "/pages/components/systemSettings/systemSettings" |
       "/pages/components/timeNow/timeNow" |
       "/pages/components/toolsManager/toolsManager" |
       "/pages/components/unitConvert/unitConvert" |
       "/pkg-health/bmiCalculator/bmiCalculator" |
       "/pkg-device/compass/compass" |
       "/pkg-more/destinyPanel/destinyPanel" |
       "/pkg-more/directionEasterEgg/directionEasterEgg" |
       "/pkg-more/emergencyShow/emergencyShow" |
       "/pkg-more/localPersona/localPersona" |
       "/pkg-more/moreTools/moreTools" |
       "/pkg-more/procrastinationStarter/procrastinationStarter" |
       "/pkg-more/resultCardFactory/resultCardFactory" |
       "/pkg-more/reverseDecider/reverseDecider" |
       "/pkg-more/timeCapsule/timeCapsule" |
       "/pkg-more/toolBlindBox/toolBlindBox";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
